AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Instance > Boston-Instance

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Resource Identity"
        Parameters:
          - StackExportPrefix
          - pEnvironment
          - pResourceName
      - Label:
          default: "InfraStack Resource"
        Parameters:
          - VPC
          - Subnet1
      - Label:
          default: "Instance Configuration"
        Parameters:
          - pKeyPair
          - pTargetPort

Parameters:
  StackExportPrefix:
    Type: "String"
    Default: "project-dev-t2"
  pEnvironment:
    Type: "String"
    Default: "dev"
  pResourceName:
    Type: String
    Default: "Boston"
    AllowedPattern: "[A-Za-z0-9]*"
    MaxLength: 12
  pKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: "working"
  pTargetPort:
    Type: Number
    Default: 80



  ## :: InfraStack Resource
  # NOTE : If this template is attached to InfraStack, then replace the following:
  # Fn::ImportValue: !Sub "${StackExportPrefix}-${VPC}" -> !Ref VPC
  # Fn::ImportValue: !Sub "${StackExportPrefix}-${Subnet1}" -> !Ref Subnet1
  # Fn::ImportValue: !Sub "${StackExportPrefix}-${SGInstance}" -> !Ref SGInstance

  VPC:
    Type: String
    Default: "VPC"
  Subnet1:
    Type: String
    Default: "PublicSubnet1"
  SGInstance:
    Type: String
    Default: "WebServerSG"

Mappings:
  InstanceMap:
    InstanceType:
      dev: "t2.micro"
      test: "t2.micro"
      stage: "t2.micro"
      prod: "t2.micro"
  ImageMap:
    us-east-1:
      dev: "ami-051f8a213df8bc089"


Resources:
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:

        - Fn::ImportValue: !Sub "${StackExportPrefix}-IAMRole-WebServerRole"

  Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - IamInstanceProfile
    Properties:
      IamInstanceProfile: !Ref IamInstanceProfile
      ImageId: !FindInMap
        - ImageMap
        - !Ref "AWS::Region"
        - !Ref pEnvironment
      InstanceType: !FindInMap
        - InstanceMap
        - "InstanceType"
        - !Ref pEnvironment
      KeyName: !Ref pKeyPair
      NetworkInterfaces:
        - DeleteOnTermination: true
          AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue: !Sub "${StackExportPrefix}-${Subnet1}"
          GroupSet:
            - Fn::ImportValue: !Sub "${StackExportPrefix}-SG-${SGInstance}"
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            sudo yum update -y
            yum update -y
            sudo yum install python3 -y
            sudo yum install python3-pip -y

      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: StackExportPrefix
          Value: !Ref StackExportPrefix
        - Key: pEnvironment
          Value: !Ref pEnvironment
        - Key: Name
          Value: !Sub "${StackExportPrefix}-${pResourceName}-EC2"


Outputs:
  Instance:
    Description: A reference to the Instance
    Value: !Ref Instance
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-WebInstance"
  InstancePrivateIp:
    Description: A reference to the Instance PrivateIp
    Value: !GetAtt Instance.PrivateIp
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-InstancePrivateIp"
